version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        # 支持1.8、1.10、1.11、1.12、1.13、1.14、1.15、1.16八个版本
        golangVersion: 1.12
        # 构建命令
        commands: |
          make test
        # 非必填字段，开启后表示将构建产物暂存，但不会上传到制品库中，7天后自动清除
        artifacts:
            # 构建产物名字，作为产物的唯一标识可向下传递，支持自定义，默认为BUILD_ARTIFACT。在下游可以通过${BUILD_ARTIFACT}方式引用来获取构建物地址
          - name: BUILD_ARTIFACT
            # 构建产物获取路径，是指代码编译完毕之后构建物的所在路径
            path:
              - ./output
triggers:
  pr:
    branches:
      include:
        - master
